### ISSUE TITLE
Tezbox Desktop Wallet

### ISSUE THREAD

**Issue by IntricateCoin** [tezbox/desktop-wallet#14]
Unable to connect to desktop wallet. Any help would be greatly appreciated. 

This account has not been added to the blockchain yet - please wait for a baker to include this in a block before you can use this account. This error may also show if your device can't connect to the Tezos Network.

Error
level N/A
Not Connected
https://mainnet.tezrpc.me

**Comment by Heart8reak** [comment]
Hello 


How reconnect my account to the blockchain 

Thanks

Carlos

**Comment by IntricateCoin** [comment]
resolved issue with out team. closing ticket. no response any way. Good luck to all you not so savy people. May the force be with you.

**Comment by Heart8reak** [comment]
Thanks buddy for your motivation
