### ISSUE TITLE
Trezor for Desktop Wallet on Mac not working

### ISSUE THREAD

**Issue by Sm00g15** [tezbox/desktop-wallet#2]
I have the latest software, and latest firmware on Trezor Model T.

After clicking "Link the Device" it shows a modal that says "Check your Trezor for address".
Afterwards, I click on the "Device" button on the Trezor and both screens go blank (TezBox/Trezor).

Same exact situation happens when I click the "Host" button.

**Comment by stephenandrews** [comment]
Host button? I'm not familiar with that, could you explain?

**Comment by Sm00g15** [comment]
Yeah for sure. If you have a Trezor Model T and you click "Link Tezbox" on the TezBox software it comes up with a binary option on the Model T screen that asks whether you want to enter password on "Host" (meaning TezBox) or "Device"

**Comment by stephenandrews** [comment]
Oh ok, right I must have that disabled on my device. For now that's not working - I believe that would require some additional work. I will investigate that and try to push out a patch asap

**Comment by Sm00g15** [comment]
Cool, sounds good.

**Comment by stephenandrews** [comment]
Good news, passphrase support has been completed on our development version and has passed testing on Windows. Will be running through testing on MacOS, and hope to post a release today/tomorrow. Thanks!

**Comment by Sm00g15** [comment]
you're very welcome, awesome job! thanks for the update

**Comment by stephenandrews** [comment]
Latest release should fix this: https://github.com/tezbox/desktop-wallet/releases/tag/2.0.1
