### ISSUE TITLE
Importing ICO Fundraiser Keys on OSX?

### ISSUE THREAD

**Issue by skaht** [tezbox/desktop-wallet#3]
Activated funds using https://stephenandrews.github.io/activatez/ several months back.  Was wondering if a prior activation creates an issue with importing the keys?  

As a potential Plan B for importing private keys, how can one synthesize an **edsk/edesk** formatted key if they only know the 64 digit raw hexadecimal private key?  

For instance, I posted https://www.reddit.com/r/tezos/comments/8n58a6/nutz_and_boltz_for_computing_tezos_ico_private/ about 5 months ago with a valid but bogus test vector <15 BIP 39 seed words, email address, ICO password> to synthesize private 64-digit private keys using bitcoin-explorer command lines.

**15 BIP 39 Seed Words:** health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge
**Email Address:** oh@mail.com
**ICO Account Password:** Hf12@ahgw895jnqGG

```% echo "health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge" | bx mnemonic-to-seed -p oh@mail.comHf12@ahgw895jnqGG | cut -c 1-64```
**f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6**

Other minor suggestions for app improvement:

1. In the menu under **Tezbox-Wallet**, end users need a means to query the version of the application being used. (Also ran into the BIP 39 passphrase issue that v2.01 has fixed.)

2. When using a **Model T**, the address displayed on the Trezor device needs to be displayed in parallel with the **Tezbox-Wallet** app to avoid requiring end users to write down the hardware wallet address to compare later to the address later generated by the **Tezbox-Wallet** app.

Thanks in advance for any assistance...

**Comment by stephenandrews** [comment]
Firstly, I don't know of any issues with importing ICO keys with MacOS, but I can test it again. Are you getting a specific error?

You can manually create an edsk here: https://stephenandrews.github.io/eztz/ - just enter your seed, then email/password as a single string as the passphrase (as you have done in your example). Make sure the pkh matches your ICO address.

Re your other queries:

1) Will add a version no. to the settings page soon. What bip39 issue did you get?

2) There's no way to do this currently - the address is displayed on the app to confirm that it is ok to send to TezBox, As in - there's no way to retrieve that address until you confirm it on the device.

**Comment by skaht** [comment]
Thanks for the quick response.  

Tried entering the data multiple times with double and triple checking all the manual entries. The specific message replied after depressing the **RESTORE TEZBOX** button was:

 **Uh-oh** Activation was unsuccessful - please ensure the code is right, or leave it blank. **My bad!!!**  

I forgot to leave the activation code blank.  The import completed successfully:-)

**Comment by skaht** [comment]
FYSA - Did notice that there is no base58check checksum error checking feedback supplied back to an end user when they desire to send funds to a destination address.

```% echo fc65ad23ba5403da45004780c11332fe00bee4b6 | sed 's/^/a19f/' | bx base58check-encode -v 6```
**tz1iean4ArF6YU8pGUup73FhoWXJr1Nw3wEo**

```% echo tz1iean4ArF6YU8pGUup73FhoWXJr1Nw3wEo | bx base58check-decode``` 
wrapper
{
    checksum 147378805
    payload a19ffc65ad23ba5403da45004780c11332fe00bee4b6
    version 6
}

**Comment by stephenandrews** [comment]
Thanks - glad that worked out. Will add better client side validation.

**Comment by stephenandrews** [comment]
Added ner issue #4

**Comment by stephenandrews** [comment]
new*

**Comment by skaht** [comment]
Thanks for the URL above. I'm examining the https://github.com/TezTech/eztz package that https://stephenandrews.github.io/eztz/ references concerning the creation of **edsk** formatted private key.  

Does **edsk** imply the secret key is to use ed25519 elliptic curve? 

It appears 256 bits of chain code is bundled with the secret as the result of an hmac-sha512 operation.  Is it necessary for the chain code to be bundled with a 256-bit key? 

Applying the following test vector to https://stephenandrews.github.io/eztz/

**15 BIP 39 Seed Words:** health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge
**Passphrase:** oh@mail.comHf12@ahgw895jnqGG

The resulting **sk** is: **edskSAhCQs733omXJSpWByzFpVwdH56TtnGMH7Cno7JyMMScnm6RjDb46YW2oVz1SGB9oD8eKtJfCYUcDnSn8PaH3w4cvxUJns**

```% echo edskSAhCQs733omXJSpWByzFpVwdH56TtnGMH7Cno7JyMMScnm6RjDb46YW2oVz1SGB9oD8eKtJfCYUcDnSn8PaH3w4cvxUJns | bx base58check-decode```
wrapper
{
    checksum 3500198555
    payload f64e07f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6e3d04f6fd97888f4d825d7586da00062ff4584064a6a854cdd164f8a4897894c
    version 43
}

```% echo f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6e3d04f6fd97888f4d825d7586da00062ff4584064a6a854cdd164f8a4897894c | sed 's/^/f64e07/' | bx base58check-encode -v 43```
edskSAhCQs733omXJSpWByzFpVwdH56TtnGMH7Cno7JyMMScnm6RjDb46YW2oVz1SGB9oD8eKtJfCYUcDnSn8PaH3w4cvxUJns

From the base58check-encode version number and the hex sed substitution regex hex digits, I notice that the results match https://github.com/TezTech/eztz/blob/master/src/main.js#L30.

    Base16(43)  = 0x2b
    Base16(246) = 0xf6
    Base16(78)  = 0x4e
    Base16(7)   = 0x07

This means I semantically understand where the **edsk** prefix is coming from. 

I believe the 256-bit secret key is:
```% echo f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6e3d04f6fd97888f4d825d7586da00062ff4584064a6a854cdd164f8a4897894c | cut -c 1-64```
**f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6**

which can also be extracted using the following technique, which ignores checksum error checking:
```% echo edskSAhCQs733omXJSpWByzFpVwdH56TtnGMH7Cno7JyMMScnm6RjDb46YW2oVz1SGB9oD8eKtJfCYUcDnSn8PaH3w4cvxUJns | bx base58-decode | cut -c 9-72```
**f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6**

and can also be computed using the following technique:
```% echo "health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge" | bx mnemonic-to-seed -p oh@mail.comHf12@ahgw895jnqGG | cut -c 1-64```
**f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6**

However, I'm not yet understanding where the **de facto 256 bits of chain code** comes from:
```% echo f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef6e3d04f6fd97888f4d825d7586da00062ff4584064a6a854cdd164f8a4897894c | cut -c 65-128```
e3d04f6fd97888f4d825d7586da00062ff4584064a6a854cdd164f8a4897894c

```% echo "health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge" | bx mnemonic-to-seed -p oh@mail.comHf12@ahgw895jnqGG | cut -c 65-128```
*71300b3c60784c06850f4cbc5fb61f21959953ec3e1cc1e4061c2e9eb8d8626c* 
would be the chaincode for BTC, but not apparently for XTZ.  The diagram below shows what Bitcoin does:

![mbc2_0507](https://user-images.githubusercontent.com/6238506/48304429-6ea9cc00-e4e7-11e8-8a46-a53eedf05f14.png)

source: https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch05.asciidoc#fig_5_7

A few important details are missing in the diagram above, which pops out for our test vector above using the either of the following two approaches:

```% echo "health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge" | bx mnemonic-to-seed -p oh@mail.comHf12@ahgw895jnqGG```
f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef671300b3c60784c06850f4cbc5fb61f21959953ec3e1cc1e4061c2e9eb8d8626c

```% stretch -f sha512 -r 2048 "health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge" "mnemonicoh@mail.comHf12@ahgw895jnqGG" | sed 's/^b.//' | sed 's/.$//' | bx base64-decode | bx base16-encode```
f9ca48ee56f27a510c90c2bc61d523a8032b67a7f88d2ba6b838f190bee13ef671300b3c60784c06850f4cbc5fb61f21959953ec3e1cc1e4061c2e9eb8d8626c

where the Python stretch command is available at https://pypi.org/project/stretch/.  From analyzing the stretch command, it calls pbkdf2 with the following BIP39 parameters: 

stretch->passlib.pbkdf2( secret, “mnemonic”+salt, rounds=2048, keylength=64, sha512 )

that is consistent with details found at 
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#from-mnemonic-to-seed.

The question is, to properly compute the XTZ chain code for the test vector above using different code bases (to make a very basic cybersecurity **Common Criteria EAL** assertion), are the pbkdf2 parameters used by Tezos below correct?

    secret       = BIP39 seed words = "health boil host ostrich fire spike body solar collect harvest catalog cup mix tattoo merge"
    salt         =  "mnemonic" + email + password = "mnemonicoh@mail.comHf12@ahgw895jnqGG"
    rounds       = 32768
    keylength    = 256
    hashfunction = sha512
