### ISSUE TITLE
Redelegation fails

### ISSUE THREAD

**Issue by jontra000** [tezbox/desktop-wallet#8]
Attempting to change the delegate in the windows wallet fails with 'Uh-oh! Delegation Failed'

I've tried with both low and medium fees, and I've tried both changing to a custom delegate and undelegating.

Normal transactions are working fine.

**Comment by erf** [comment]
Do you have XTZ on the address you are trying to change delegation on? It needs XTZ for chaning fee.

**Comment by jontra000** [comment]
Turned out to be a duplicate of https://github.com/tezbox/web-wallet/issues/32
